services:
  postgres:
    image: postgres:16-alpine
    container_name: ala-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ala_hr
      POSTGRES_USER: ala_admin
      POSTGRES_PASSWORD: ala_secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ala-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ala-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://ala_admin:ala_secret@postgres:5432/ala_hr"
      NEXTAUTH_SECRET: "alabuga-nextauth-secret-key-for-hackathon-2025"
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    networks:
      - ala-network

volumes:
  postgres_data:

networks:
  ala-network:
    driver: bridge
